const headerMappings = {
    collegiateNumber: 'Número de colegiado',
    DRONumber: 'Número de DRO',
    fullName: 'Nombre completo',
    memberType: 'Tipo de miembro',
    classification: 'Clasificación',
    specialties: 'Especialidades',
    mainProfessionalActivity: 'Actividad profesional principal',
    professionalLicense: 'Cédula profesional',
    dateOfAdmission: 'Fecha de ingreso',
    gender: 'Género',
    dateOfBirth: 'Fecha de nacimiento',
    age: 'Edad',
    university: 'Universidad',
    municipalityOfLabor: 'Municipio de trabajo',
    authorizationToShareInfo: 'Autorización para compartir información',
    lifeInsurance: 'Seguro de vida',
    lifeInsureID: 'Póliza de seguro de vida',
    homePhone: 'Número de casa',
    officePhone: 'Número de oficina',
    cellphone: 'Número de celular',
    email: 'Correo electrónico',
    homeAddress: 'Domicilio de particular',
    workAddress: 'Domicilio de trabajo',
    emergencyContactName: 'Nombre de contacto de emergencia',
    linkCV: 'Link de CV',
    positionsInCouncil: 'Cargos en consejos directivos',
    capacitationHours: 'Horas de capacitación',
};

export default headerMappings;
