# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Tests in /caeq-backend

on:
    pull_request:
        branches:
            - master # Change this to your main branch name
            - develop # Change this to your main branch name
            - test # Change this to your main branch name

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install project dependencies
              run: |
                  cd CAEQ/caeq-backend  # Adjust the path to your caeq-backend directory
                  npm install
              working-directory: ${{ github.workspace }}/CAEQ

            - name: Run tests
              run: |
                  cd CAEQ/caeq-backend  # Adjust the path to your caeq-backend directory
                  npm install
              working-directory: ${{ github.workspace }}/CAEQ
