# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Tests in /caeq-backend

on:
    pull_request:
        branches:
            - master # Change this to your main branch name
            - develop # Change this to your main branch name
            - test # Change this to your main branch name

jobs:
    UnitTesting:
        runs-on: ubuntu-latest

        env:
            STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
            GOOGLE_CREDENTIALS_FILE: ${{secrets.GOOGLE_CREDENTIALS_FILE}}
            NODE_ENV: testing
            DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}
            DATABASE_NAME_TEST: ${{ secrets.DATABASE_NAME_TEST }}
            DATABASE_NAME_PROD: ${{ secrets.DATABASE_NAME_PROD }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            FRONT_DOMAIN: ${{ secrets.FRONT_DOMAIN }}
            API_KEY: ${{ secrets.API_KEY }}
            AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
            PROJECT_ID: ${{ secrets.PROJECT_ID }}
            MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
            APP_ID: ${{ secrets.APP_ID }}
            MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
            JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
            OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID }}
            OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
            OAUTH_ACCESS_TOKEN: ${{ secrets.OAUTH_ACCESS_TOKEN }}
            OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
            SERVER_PORT: 5000
            ARCHITECTS_DATA_FILEPATH: './models/data/RELACION CAEQ 2022-2023.csv'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: ${{ github.workspace }}/caeq-backend

            - name: Set google credentials file
              run: |
                  mkdir -p keys/ && echo $GOOGLE_CREDENTIALS_CONTENT > keys/caeq-system-firebase-adminsdk-3ud6m-6bda1b0c0e.json
              working-directory: ${{ github.workspace }}/caeq-backend

            - name: Run tests
              run: |
                  npm run test
              working-directory: ${{ github.workspace }}/caeq-backend
